import "./globals.css";

import Providers from "@/components/templates/Providers";
import StateProviders from "@/components/templates/StateProviders";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <StateProviders>
            <div className="text-neutral-950 antialiased bg-neutral-100 dark:bg-neutral-700">
              {children}
            </div>
          </StateProviders>
        </Providers>
      </body>
    </html>
  );
}
